import os
from dotenv import load_dotenv

load_dotenv()

SERVICE_NAME = os.getenv("SERVICE_NAME", "recommendation-service")
SERVICE_PORT = int(os.getenv("SERVICE_PORT", 3006))

MYSQL_HOST = os.getenv("MYSQL_HOST", "localhost")
MYSQL_PORT = os.getenv("MYSQL_PORT", "3306")
MYSQL_USER = os.getenv("MYSQL_USER", "root")
MYSQL_PASSWORD = os.getenv("MYSQL_PASSWORD", "123456")
MYSQL_DATABASE = os.getenv("MYSQL_DATABASE", "recommendation_service")

DATABASE_URL = f"mysql+pymysql://{MYSQL_USER}:{MYSQL_PASSWORD}@{MYSQL_HOST}:{MYSQL_PORT}/{MYSQL_DATABASE}"

AMQP_URL = os.getenv("AMQP_URL")
MONITORING_EVENTS_QUEUE = os.getenv("MONITORING_EVENTS_QUEUE", "monitoring_events")
RECOMMENDATIONS_QUEUE = os.getenv("RECOMMENDATIONS_QUEUE", "recommendations")
ACTIVITY_DETAILS_REQUEST_QUEUE = os.getenv("ACTIVITY_DETAILS_REQUEST_QUEUE", "activity_details_request")
ACTIVITY_DETAILS_RESPONSE_QUEUE = os.getenv("ACTIVITY_DETAILS_RESPONSE_QUEUE", "activity_details_response")
SESSION_CONFIG_REQUEST_QUEUE = os.getenv("SESSION_CONFIG_REQUEST_QUEUE", "session_config_request")
SESSION_CONFIG_RESPONSE_QUEUE = os.getenv("SESSION_CONFIG_RESPONSE_QUEUE", "session_config_response")
LOG_SERVICE_QUEUE = os.getenv("LOG_SERVICE_QUEUE", "logs")

GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")

REDIS_URL = os.getenv("REDIS_URL")
REDIS_TOKEN = os.getenv("REDIS_TOKEN")

HTTP_TIMEOUT = int(os.getenv("HTTP_TIMEOUT", 10))
RABBITMQ_TIMEOUT = int(os.getenv("RABBITMQ_TIMEOUT", 5))
MAX_RETRIES = int(os.getenv("MAX_RETRIES", 3))
CACHE_TTL = int(os.getenv("CACHE_TTL", 300))

ACTIVITY_DETAILS_CACHE_TTL = int(os.getenv("ACTIVITY_DETAILS_CACHE_TTL", 600))
GENERATED_CONTENT_CACHE_TTL = int(os.getenv("GENERATED_CONTENT_CACHE_TTL", 3600))

INTERVENTION_CONSUMER_WORKERS = int(os.getenv("INTERVENTION_CONSUMER_WORKERS", 5))
PREFETCH_COUNT = int(os.getenv("PREFETCH_COUNT", 10))

GEMINI_RATE_LIMIT_PER_MINUTE = int(os.getenv("GEMINI_RATE_LIMIT_PER_MINUTE", 60))
GEMINI_TIMEOUT = int(os.getenv("GEMINI_TIMEOUT", 10))

CLOUDINARY_CLOUD_NAME = os.getenv("CLOUDINARY_CLOUD_NAME")
CLOUDINARY_API_KEY = os.getenv("CLOUDINARY_API_KEY")
CLOUDINARY_API_SECRET = os.getenv("CLOUDINARY_API_SECRET")