-- En MYSQL ejecutar una sola vez:
CREATE DATABASE IF NOT EXISTS auth_service CHARACTER SET utf8mb4;
CREATE DATABASE IF NOT EXISTS session_service CHARACTER SET utf8mb4;
CREATE DATABASE IF NOT EXISTS monitoring_service CHARACTER SET utf8mb4;
CREATE DATABASE IF NOT EXISTS recommendaion_service CHARACTER SET utf8mb4;
CREATE DATABASE IF NOT EXISTS analytics_service CHARACTER SET utf8mb4;
CREATE DATABASE IF NOT EXISTS monitoring_service CHARACTER SET utf8mb4;