import os
from dotenv import load_dotenv

load_dotenv()

MYSQL_HOST = os.getenv("MYSQL_HOST")
MYSQL_PORT = os.getenv("MYSQL_PORT")
MYSQL_USER = os.getenv("MYSQL_USER")
MYSQL_PASSWORD = os.getenv("MYSQL_PASSWORD")
MYSQL_DATABASE = os.getenv("MYSQL_DATABASE")

DATABASE_URL = f"mysql+pymysql://{MYSQL_USER}:{MYSQL_PASSWORD}@{MYSQL_HOST}:{MYSQL_PORT}/{MYSQL_DATABASE}"

AMQP_URL = os.getenv("AMQP_URL")

SERVICE_NAME = os.getenv("SERVICE_NAME")
SERVICE_PORT = int(os.getenv("SERVICE_PORT"))
LOG_SERVICE_QUEUE = os.getenv("LOG_SERVICE_QUEUE")
PAYMENT_EVENTS_QUEUE = os.getenv("PAYMENT_EVENTS_QUEUE", "payment_events")

JWT_SECRET_KEY = os.getenv("JWT_SECRET_KEY")
JWT_ALGORITHM = os.getenv("JWT_ALGORITHM")
JWT_EXPIRATION_HOURS = int(os.getenv("JWT_EXPIRATION_HOURS"))

MAX_EMAIL_VERIFICATION_ATTEMPTS_PER_HOUR = int(os.getenv("MAX_EMAIL_VERIFICATION_ATTEMPTS_PER_HOUR"))
EMAIL_VERIFICATION_CODE_EXPIRATION_MINUTES = int(os.getenv("EMAIL_VERIFICATION_CODE_EXPIRATION_MINUTES"))
EMAIL_VERIFICATION_RATE_LIMIT_WINDOW_MINUTES = int(os.getenv("EMAIL_VERIFICATION_RATE_LIMIT_WINDOW_MINUTES"))

MAX_LOGIN_ATTEMPTS_PER_HOUR = int(os.getenv("MAX_LOGIN_ATTEMPTS_PER_HOUR"))
LOGIN_OTP_EXPIRATION_MINUTES = int(os.getenv("LOGIN_OTP_EXPIRATION_MINUTES"))
LOGIN_RATE_LIMIT_WINDOW_MINUTES = int(os.getenv("LOGIN_RATE_LIMIT_WINDOW_MINUTES"))

MAX_REVOCATION_ATTEMPTS_PER_HOUR = int(os.getenv("MAX_REVOCATION_ATTEMPTS_PER_HOUR"))
REVOCATION_CODE_EXPIRATION_MINUTES = int(os.getenv("REVOCATION_CODE_EXPIRATION_MINUTES"))
REVOCATION_RATE_LIMIT_WINDOW_MINUTES = int(os.getenv("REVOCATION_RATE_LIMIT_WINDOW_MINUTES"))
EMAIL_QUEUE = os.getenv("EMAIL_QUEUE", "emails")