import os
from dotenv import load_dotenv

load_dotenv()

SERVICE_NAME = os.getenv("SERVICE_NAME", "monitoring-service")
SERVICE_PORT = int(os.getenv("SERVICE_PORT", 3008))

MYSQL_HOST = os.getenv("MYSQL_HOST", "localhost")
MYSQL_PORT = int(os.getenv("MYSQL_PORT", 3306))
MYSQL_USER = os.getenv("MYSQL_USER", "root")
MYSQL_PASSWORD = os.getenv("MYSQL_PASSWORD", "")
MYSQL_DATABASE = os.getenv("MYSQL_DATABASE", "monitoring_service")

AMQP_URL = os.getenv("AMQP_URL")
MONITORING_EVENTS_QUEUE = os.getenv("MONITORING_EVENTS_QUEUE", "monitoring_events")
LOG_SERVICE_QUEUE = os.getenv("LOG_SERVICE_QUEUE", "logs")
ACTIVITY_EVENTS_QUEUE = os.getenv("ACTIVITY_EVENTS_QUEUE", "activity_events")
MONITORING_WEBSOCKET_EVENTS_QUEUE = os.getenv("MONITORING_WEBSOCKET_EVENTS_QUEUE", "monitoring_websocket_events")
RECOMMENDATIONS_QUEUE = os.getenv("RECOMMENDATIONS_QUEUE", "recommendations")
INTERVENTION_EVALUATIONS_QUEUE = os.getenv("INTERVENTION_EVALUATIONS_QUEUE", "intervention_evaluations")

REDIS_URL = os.getenv("REDIS_URL")
REDIS_TOKEN = os.getenv("REDIS_TOKEN")

RECOMMENDATION_CONSUMER_WORKERS = int(os.getenv("RECOMMENDATION_CONSUMER_WORKERS", 5))
RECOMMENDATION_PREFETCH_COUNT = int(os.getenv("RECOMMENDATION_PREFETCH_COUNT", 10))

CLUSTERING_MIN_SAMPLES = int(os.getenv("CLUSTERING_MIN_SAMPLES", 50))
CLUSTERING_UPDATE_FREQUENCY = int(os.getenv("CLUSTERING_UPDATE_FREQUENCY", 100))
CLUSTERING_MIN_CLUSTER_SIZE = int(os.getenv("CLUSTERING_MIN_CLUSTER_SIZE", 10))
FEATURE_BUFFER_SIZE = int(os.getenv("FEATURE_BUFFER_SIZE", 300))
TEMPORAL_WINDOWS = [int(x) for x in os.getenv("TEMPORAL_WINDOWS", "10,30,60,150").split(",")]

COOLDOWN_VIBRATION_BASE = int(os.getenv("COOLDOWN_VIBRATION_BASE", 30))
COOLDOWN_INSTRUCTION_BASE = int(os.getenv("COOLDOWN_INSTRUCTION_BASE", 60))
COOLDOWN_PAUSE_BASE = int(os.getenv("COOLDOWN_PAUSE_BASE", 180))
COOLDOWN_EFFECTIVENESS_MULTIPLIER = float(os.getenv("COOLDOWN_EFFECTIVENESS_MULTIPLIER", 0.5))

STATE_STABILITY_THRESHOLD = int(os.getenv("STATE_STABILITY_THRESHOLD", 5))
DECISION_CONFIDENCE_THRESHOLD = float(os.getenv("DECISION_CONFIDENCE_THRESHOLD", 0.6))

INTERVENTION_EVALUATION_DELAY = int(os.getenv("INTERVENTION_EVALUATION_DELAY", 90))

DATABASE_URL = f"mysql+pymysql://{MYSQL_USER}:{MYSQL_PASSWORD}@{MYSQL_HOST}:{MYSQL_PORT}/{MYSQL_DATABASE}"